# Generated by Django 4.1.5 on 2023-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transactionlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlike',
            name='id',
        ),
        migrations.AddField(
            model_name='transactionlike',
            name='transactionlike_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
