# Generated by Django 4.1.7 on 2023-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='ticket', max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
