# Generated by Django 4.1.7 on 2023-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='stock',
            field=models.IntegerField(default=1, max_length=30000),
        ),
    ]
