# Generated by Django 4.1.7 on 2023-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('recycle', models.CharField(max_length=30)),
            ],
        ),
    ]
