# Generated by Django 4.1.5 on 2023-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://trolleymate.co.uk/assets/img/error_404.jpeg'),
            preserve_default=False,
        ),
    ]
